export const SET_NEWS = 'SET_NEWS'

export const SET_RECRUITMENT = 'SET_RECRUITMENT'

export const SET_NEWSINDEX = 'SET_NEWSINDEX'

export const SET_NEWSRECORDLIST ='SET_NEWSRECORDLIST'

export const SET_ISWX = 'SET_ISWX'
